ALTER TABLE `Payment` MODIFY COLUMN `method` ENUM('ONLINE', 'CASH', 'UPI', 'NEFT', 'RTGS', 'CHEQUE', 'CREDIT_CARD') NOT NULL;
ALTER TABLE `MaintenancePayment` MODIFY COLUMN `method` ENUM('ONLINE', 'CASH', 'UPI', 'NEFT', 'RTGS', 'CHEQUE', 'CREDIT_CARD') NOT NULL;
