import type { Metadata } from "next";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Terms & Conditions – Oasis Venetia Heights",
  description:
    "Terms and conditions for using the Oasis Venetia Heights electricity management portal",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-semibold text-gray-900 mb-3">{title}</h2>
      <div className="text-gray-700 leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms &amp; Conditions</h1>
        <p className="text-sm text-gray-500">Last updated: 22 July 2026</p>
      </div>

      <Section title="1. Introduction">
        <p>
          These terms govern use of the Oasis Venetia Heights Electricity Management Portal
          accessible at{" "}
          <a href="https://oasisvenetia.in" className="text-blue-600 hover:underline">
            https://oasisvenetia.in
          </a>
          . By using this portal, you agree to these terms.
        </p>
        <p>Operated by: Oasis Group of Companies, A-77, Sector 2, Noida.</p>
      </Section>

      <Section title="2. Services">
        <p>
          The portal allows residents to view electricity consumption bills and make online
          payments. Bills are generated by Oasis Group of Companies based on meter readings
          recorded by authorised staff. Access is limited to registered residents of Oasis
          Venetia Heights.
        </p>
      </Section>

      <Section title="3. Payment Terms">
        <ul className="list-disc pl-6 space-y-1">
          <li>Payments are processed via Razorpay Payment Gateway.</li>
          <li>
            Accepted payment methods: UPI, credit cards, debit cards, net banking.
          </li>
          <li>
            The amount displayed at checkout is the final payable amount, inclusive of all
            applicable charges.
          </li>
          <li>
            Payments are credited to your account upon successful confirmation from Razorpay.
          </li>
        </ul>
      </Section>

      <Section title="4. Refund & Cancellation Policy">
        <ul className="list-disc pl-6 space-y-1">
          <li>Payments once successfully processed are non-refundable.</li>
          <li>
            If a payment is deducted but your bill status does not update within 24 hours,
            contact us at{" "}
            <a href="mailto:info@oasis.in" className="text-blue-600 hover:underline">
              info@oasis.in
            </a>{" "}
            with your transaction ID.
          </li>
          <li>
            Duplicate or excess payments, if verified, will be adjusted against the next
            billing cycle.
          </li>
          <li>Cancellation of a payment once initiated is not possible.</li>
        </ul>
      </Section>

      <Section title="5. Billing Disputes">
        <p>
          Disputes regarding bill amounts must be raised within 30 days of the bill date by
          contacting{" "}
          <a href="mailto:info@oasis.in" className="text-blue-600 hover:underline">
            info@oasis.in
          </a>{" "}
          with your flat number and bill number.
        </p>
      </Section>

      <Section title="6. Privacy & Data">
        <ul className="list-disc pl-6 space-y-1">
          <li>
            Payment card and UPI details are handled exclusively by Razorpay and are not stored
            on our servers.
          </li>
          <li>
            Personal information (name, flat number, email) is used solely for billing and
            communication purposes.
          </li>
          <li>
            We do not share your data with third parties except as required by law.
          </li>
        </ul>
      </Section>

      <Section title="7. Governing Law">
        <p>
          These terms are governed by the laws of India. Any disputes shall be subject to the
          exclusive jurisdiction of the courts of Noida, Uttar Pradesh.
        </p>
      </Section>

      <Section title="8. Changes to Terms">
        <p>
          Oasis Group of Companies reserves the right to update these terms at any time.
          Continued use of the portal after changes constitutes acceptance of the updated terms.
        </p>
      </Section>

      <Section title="9. Contact Us">
        <div className="space-y-1">
          <p>
            <strong>Oasis Group of Companies</strong>
          </p>
          <p>A-77, Sector 2, Noida</p>
          <p>+91-8010-111-777</p>
          <p>
            <a href="mailto:info@oasis.in" className="text-blue-600 hover:underline">
              info@oasis.in
            </a>
          </p>
          <p>
            <a
              href="https://www.oasis.in/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
            >
              www.oasis.in
            </a>
          </p>
        </div>
      </Section>
    </div>
  );
}
