import { config } from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
config({ path: path.join(__dirname, "../.env") });
config({ path: path.join(__dirname, "../.env.local") });
import { PrismaMariaDb } from "@prisma/adapter-mariadb";
import { PrismaClient } from "@prisma/client";
const _u = process.env.DATABASE_URL ?? "";
const _p = new URL(_u);
const _ssl = process.env.DATABASE_SSL === "true" || _p.hostname !== "localhost";
const prisma = new PrismaClient({ adapter: new PrismaMariaDb({ url: _u, ssl: _ssl ? { rejectUnauthorized: false } : false }) });
const rows = await prisma.connection.findMany({ select: { flatNo: true, meterNo: true }, take: 15, orderBy: { flatNo: "asc" } });
console.log("Sample meter numbers:");
rows.forEach(r => console.log(`  flatNo=${r.flatNo}  meterNo=${r.meterNo ?? "NULL"}`));
const withMeter = await prisma.connection.count({ where: { meterNo: { not: null } } });
const total = await prisma.connection.count();
const sameAsFlatNo = await prisma.$queryRaw`SELECT COUNT(*) as cnt FROM Connection WHERE meterNo = flatNo`;
console.log(`\nTotal: ${total}, With meterNo: ${withMeter}, meterNo same as flatNo: ${JSON.stringify(sameAsFlatNo)}`);
await prisma.$disconnect();
